vpc:
  name: dev-main-vpc
  cidr: 10.20.0.0/16
  azs: [ap-northeast-2a, ap-northeast-2b, ap-northeast-2c]
  private_subnets: [10.20.1.0/24, 10.20.2.0/24, 10.20.3.0/24]
  public_subnets: [10.20.101.0/24, 10.20.102.0/24, 10.20.103.0/24]
  nat:
    enable_nat_gateway: true
    single_nat_gateway: true
    one_nat_gateway_per_az: false
  tags:
    Environment: dev