name: terraform apply

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: "Environment branch"
        required: true
        type: choice
        option:
          - dev
          - stg
          - prd
      region:
        description: "AWS Region"
        required: true
        type: choice
        option:
          - us-west-2
          - eu-west-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: ./terraform

    steps:
      # Dropdown으로 선택한 브랜치 Checkout
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set environment & region
        run: |
          echo "environment=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          echo "region=${{ github.event.inputs.region }}" >> $GITHUB_OUTPUT
          if [ "${region}" = "us-west-2" ]; then
            echo "region_code=us" >> $GITHUB_OUTPUT
          else [ "${region}" = "eu-west-1" ]; then
            echo "region_code=eu" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=terraform-${environment}/terraform.tfstate" \
            -backend-config="region=${region}"

      - name: Terraform Validate & Plan
        run: |
          terraform plan
          terraform validate

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file="./tfvars/${environment}-${region_code}.tfvars" \
            -auto-approve